from __future__ import annotations

"""Stable issue codes for auditing and dashboards."""

# Document / extraction
EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
SCANNED_PDF_SUSPECTED = "SCANNED_PDF_SUSPECTED"

# Sections
SECTION_MISSING_TITLE = "SECTION_MISSING_TITLE"
SECTION_EMPTY = "SECTION_EMPTY"

# Pricing rules
PRICING_RULE_MISSING_TEXT = "PRICING_RULE_MISSING_TEXT"
PRICING_RULE_LOW_CONFIDENCE = "PRICING_RULE_LOW_CONFIDENCE"
PRICING_RULE_PERCENT_AMBIGUOUS = "PRICING_RULE_PERCENT_AMBIGUOUS"

# Surcharge tables
SURCHARGE_TABLE_NO_ROWS = "SURCHARGE_TABLE_NO_ROWS"
SURCHARGE_TABLE_MISSING_TYPE = "SURCHARGE_TABLE_MISSING_TYPE"
SURCHARGE_ROW_INCOMPLETE = "SURCHARGE_ROW_INCOMPLETE"

# Discount tiers
DISCOUNT_TIER_MISSING_PERCENT = "DISCOUNT_TIER_MISSING_PERCENT"
DISCOUNT_WEIGHT_RANGE_INVALID = "DISCOUNT_WEIGHT_RANGE_INVALID"
DISCOUNT_TIER_DUPLICATE_SCOPE = "DISCOUNT_TIER_DUPLICATE_SCOPE"

# Service terms
SERVICE_TERM_SHORT_SNIPPET = "SERVICE_TERM_SHORT_SNIPPET"

# Consistency
INCONSISTENT_PERCENT_RANGE = "INCONSISTENT_PERCENT_RANGE"
