from __future__ import annotations

"""Stable issue codes for auditing and dashboards."""

# Document / extraction
EMPTY_EXTRACTION = "EMPTY_EXTRACTION"
NO_SERVICE_TERMS = "NO_SERVICE_TERMS"

# Metadata
METADATA_MISSING_CUSTOMER = "METADATA_MISSING_CUSTOMER"
METADATA_MISSING_ACCOUNT = "METADATA_MISSING_ACCOUNT"
METADATA_MISSING_CARRIER = "METADATA_MISSING_CARRIER"
METADATA_LOW_CONFIDENCE = "METADATA_LOW_CONFIDENCE"

# Service terms
SERVICE_TERM_MISSING_TYPE = "SERVICE_TERM_MISSING_TYPE"
SERVICE_TERM_MISSING_DISCOUNT = "SERVICE_TERM_MISSING_DISCOUNT"
SERVICE_TERM_LOW_CONFIDENCE = "SERVICE_TERM_LOW_CONFIDENCE"

# Surcharges
SURCHARGE_MISSING_NAME = "SURCHARGE_MISSING_NAME"
SURCHARGE_MISSING_MODIFICATION = "SURCHARGE_MISSING_MODIFICATION"
SURCHARGE_LOW_CONFIDENCE = "SURCHARGE_LOW_CONFIDENCE"

# DIM rules
DIM_RULE_MISSING_DIVISOR = "DIM_RULE_MISSING_DIVISOR"

# Consistency
INCONSISTENT_PERCENT_RANGE = "INCONSISTENT_PERCENT_RANGE"
DUPLICATE_SERVICE_TERM = "DUPLICATE_SERVICE_TERM"
